var namespaceOpenMesh =
[
    [ "Attributes", "namespaceOpenMesh_1_1Attributes.html", "namespaceOpenMesh_1_1Attributes" ],
    [ "Concepts", "namespaceOpenMesh_1_1Concepts.html", "namespaceOpenMesh_1_1Concepts" ],
    [ "Decimater", "namespaceOpenMesh_1_1Decimater.html", "namespaceOpenMesh_1_1Decimater" ],
    [ "GenProg", "namespaceOpenMesh_1_1GenProg.html", null ],
    [ "Geometry", null, [
      [ "QuadricT", "classOpenMesh_1_1Geometry_1_1QuadricT.html", "classOpenMesh_1_1Geometry_1_1QuadricT" ]
    ] ],
    [ "IO", "namespaceOpenMesh_1_1IO.html", "namespaceOpenMesh_1_1IO" ],
    [ "Iterators", "namespaceOpenMesh_1_1Iterators.html", "namespaceOpenMesh_1_1Iterators" ],
    [ "Kernel_OSG", "namespaceOpenMesh_1_1Kernel__OSG.html", "namespaceOpenMesh_1_1Kernel__OSG" ],
    [ "Smoother", null, [
      [ "JacobiLaplaceSmootherT", "classOpenMesh_1_1Smoother_1_1JacobiLaplaceSmootherT.html", "classOpenMesh_1_1Smoother_1_1JacobiLaplaceSmootherT" ],
      [ "LaplaceSmootherT", "classOpenMesh_1_1Smoother_1_1LaplaceSmootherT.html", "classOpenMesh_1_1Smoother_1_1LaplaceSmootherT" ],
      [ "SmootherT", "classOpenMesh_1_1Smoother_1_1SmootherT.html", "classOpenMesh_1_1Smoother_1_1SmootherT" ]
    ] ],
    [ "Subdivider", null, [
      [ "Adaptive", "namespaceOpenMesh_1_1Subdivider_1_1Adaptive.html", "namespaceOpenMesh_1_1Subdivider_1_1Adaptive" ],
      [ "Uniform", "namespaceOpenMesh_1_1Subdivider_1_1Uniform.html", "namespaceOpenMesh_1_1Subdivider_1_1Uniform" ]
    ] ],
    [ "Utils", "namespaceOpenMesh_1_1Utils.html", "namespaceOpenMesh_1_1Utils" ],
    [ "VDPM", "namespaceOpenMesh_1_1VDPM.html", "namespaceOpenMesh_1_1VDPM" ],
    [ "VDPMSynthesizerViewerWidget", "classOpenMesh_1_1VDPMSynthesizerViewerWidget.html", "classOpenMesh_1_1VDPMSynthesizerViewerWidget" ],
    [ "LoopSchemeMaskT", "classOpenMesh_1_1LoopSchemeMaskT.html", "classOpenMesh_1_1LoopSchemeMaskT" ],
    [ "NormalConeT", "classOpenMesh_1_1NormalConeT.html", "classOpenMesh_1_1NormalConeT" ],
    [ "ArrayKernel", "classOpenMesh_1_1ArrayKernel.html", "classOpenMesh_1_1ArrayKernel" ],
    [ "AttribKernelT", "classOpenMesh_1_1AttribKernelT.html", "classOpenMesh_1_1AttribKernelT" ],
    [ "BaseKernel", "classOpenMesh_1_1BaseKernel.html", "classOpenMesh_1_1BaseKernel" ],
    [ "BaseMesh", "classOpenMesh_1_1BaseMesh.html", "classOpenMesh_1_1BaseMesh" ],
    [ "FinalMeshItemsT", "structOpenMesh_1_1FinalMeshItemsT.html", "structOpenMesh_1_1FinalMeshItemsT" ],
    [ "BaseHandle", "classOpenMesh_1_1BaseHandle.html", "classOpenMesh_1_1BaseHandle" ],
    [ "VertexHandle", "structOpenMesh_1_1VertexHandle.html", "structOpenMesh_1_1VertexHandle" ],
    [ "HalfedgeHandle", "structOpenMesh_1_1HalfedgeHandle.html", "structOpenMesh_1_1HalfedgeHandle" ],
    [ "EdgeHandle", "structOpenMesh_1_1EdgeHandle.html", "structOpenMesh_1_1EdgeHandle" ],
    [ "FaceHandle", "structOpenMesh_1_1FaceHandle.html", "structOpenMesh_1_1FaceHandle" ],
    [ "PolyConnectivity", "classOpenMesh_1_1PolyConnectivity.html", "classOpenMesh_1_1PolyConnectivity" ],
    [ "PolyMesh_ArrayKernel_GeneratorT", "structOpenMesh_1_1PolyMesh__ArrayKernel__GeneratorT.html", "structOpenMesh_1_1PolyMesh__ArrayKernel__GeneratorT" ],
    [ "PolyMesh_ArrayKernelT", "classOpenMesh_1_1PolyMesh__ArrayKernelT.html", null ],
    [ "PolyMeshT", "classOpenMesh_1_1PolyMeshT.html", "classOpenMesh_1_1PolyMeshT" ],
    [ "DefaultTraits", "structOpenMesh_1_1DefaultTraits.html", "structOpenMesh_1_1DefaultTraits" ],
    [ "MergeTraits", "structOpenMesh_1_1MergeTraits.html", null ],
    [ "TriConnectivity", "classOpenMesh_1_1TriConnectivity.html", "classOpenMesh_1_1TriConnectivity" ],
    [ "TriMesh_ArrayKernel_GeneratorT", "structOpenMesh_1_1TriMesh__ArrayKernel__GeneratorT.html", "structOpenMesh_1_1TriMesh__ArrayKernel__GeneratorT" ],
    [ "TriMesh_ArrayKernelT", "classOpenMesh_1_1TriMesh__ArrayKernelT.html", null ],
    [ "TriMeshT", "classOpenMesh_1_1TriMeshT.html", "classOpenMesh_1_1TriMeshT" ],
    [ "AutoPropertyHandleT", "classOpenMesh_1_1AutoPropertyHandleT.html", "classOpenMesh_1_1AutoPropertyHandleT" ],
    [ "BaseProperty", "classOpenMesh_1_1BaseProperty.html", "classOpenMesh_1_1BaseProperty" ],
    [ "Endian", "classOpenMesh_1_1Endian.html", "classOpenMesh_1_1Endian" ],
    [ "PropertyT", "classOpenMesh_1_1PropertyT.html", "classOpenMesh_1_1PropertyT" ],
    [ "PropertyT< bool >", "classOpenMesh_1_1PropertyT_3_01bool_01_4.html", "classOpenMesh_1_1PropertyT_3_01bool_01_4" ],
    [ "PropertyT< std::string >", "classOpenMesh_1_1PropertyT_3_01std_1_1string_01_4.html", "classOpenMesh_1_1PropertyT_3_01std_1_1string_01_4" ],
    [ "BasePropHandleT", "structOpenMesh_1_1BasePropHandleT.html", "structOpenMesh_1_1BasePropHandleT" ],
    [ "VPropHandleT", "structOpenMesh_1_1VPropHandleT.html", "structOpenMesh_1_1VPropHandleT" ],
    [ "HPropHandleT", "structOpenMesh_1_1HPropHandleT.html", "structOpenMesh_1_1HPropHandleT" ],
    [ "EPropHandleT", "structOpenMesh_1_1EPropHandleT.html", "structOpenMesh_1_1EPropHandleT" ],
    [ "FPropHandleT", "structOpenMesh_1_1FPropHandleT.html", "structOpenMesh_1_1FPropHandleT" ],
    [ "MPropHandleT", "structOpenMesh_1_1MPropHandleT.html", "structOpenMesh_1_1MPropHandleT" ],
    [ "PropertyContainer", "classOpenMesh_1_1PropertyContainer.html", "classOpenMesh_1_1PropertyContainer" ],
    [ "PropertyManager", "classOpenMesh_1_1PropertyManager.html", "classOpenMesh_1_1PropertyManager" ],
    [ "RandomNumberGenerator", "classOpenMesh_1_1RandomNumberGenerator.html", "classOpenMesh_1_1RandomNumberGenerator" ],
    [ "SingletonT", "classOpenMesh_1_1SingletonT.html", "classOpenMesh_1_1SingletonT" ],
    [ "vector_traits", "structOpenMesh_1_1vector__traits.html", "structOpenMesh_1_1vector__traits" ],
    [ "color_caster< osg::Color3ub, osg::Color3f >", "structOpenMesh_1_1color__caster_3_01osg_1_1Color3ub_00_01osg_1_1Color3f_01_4.html", "structOpenMesh_1_1color__caster_3_01osg_1_1Color3ub_00_01osg_1_1Color3f_01_4" ],
    [ "color_caster< osg::Color3f, osg::Color3ub >", "structOpenMesh_1_1color__caster_3_01osg_1_1Color3f_00_01osg_1_1Color3ub_01_4.html", "structOpenMesh_1_1color__caster_3_01osg_1_1Color3f_00_01osg_1_1Color3ub_01_4" ],
    [ "vector_traits< osg::Pnt4f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt4f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt4f_01_4" ],
    [ "vector_traits< osg::Pnt3f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt3f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt3f_01_4" ],
    [ "vector_traits< osg::Pnt2f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt2f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt2f_01_4" ],
    [ "vector_traits< osg::Vec4f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4f_01_4" ],
    [ "vector_traits< osg::Vec3f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec3f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec3f_01_4" ],
    [ "vector_traits< osg::Vec2f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec2f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec2f_01_4" ],
    [ "vector_traits< osg::Pnt4d >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt4d_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt4d_01_4" ],
    [ "vector_traits< osg::Pnt3d >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt3d_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt3d_01_4" ],
    [ "vector_traits< osg::Pnt2d >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt2d_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Pnt2d_01_4" ],
    [ "vector_traits< osg::Vec4d >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4d_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4d_01_4" ],
    [ "vector_traits< osg::Vec3d >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec3d_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec3d_01_4" ],
    [ "vector_traits< osg::Vec4ub >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4ub_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Vec4ub_01_4" ],
    [ "vector_traits< osg::Color3ub >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color3ub_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color3ub_01_4" ],
    [ "vector_traits< osg::Color4ub >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color4ub_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color4ub_01_4" ],
    [ "vector_traits< osg::Color3f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color3f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color3f_01_4" ],
    [ "vector_traits< osg::Color4f >", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color4f_01_4.html", "structOpenMesh_1_1vector__traits_3_01osg_1_1Color4f_01_4" ],
    [ "vector_caster< osg::Vec3f, osg::Pnt3f >", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec3f_00_01osg_1_1Pnt3f_01_4.html", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec3f_00_01osg_1_1Pnt3f_01_4" ],
    [ "vector_caster< osg::Vec4f, osg::Pnt4f >", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec4f_00_01osg_1_1Pnt4f_01_4.html", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec4f_00_01osg_1_1Pnt4f_01_4" ],
    [ "vector_caster< osg::Vec3d, osg::Pnt3d >", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec3d_00_01osg_1_1Pnt3d_01_4.html", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec3d_00_01osg_1_1Pnt3d_01_4" ],
    [ "vector_caster< osg::Vec4d, osg::Pnt4d >", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec4d_00_01osg_1_1Pnt4d_01_4.html", "structOpenMesh_1_1vector__caster_3_01osg_1_1Vec4d_00_01osg_1_1Pnt4d_01_4" ],
    [ "StripifierT", "classOpenMesh_1_1StripifierT.html", "classOpenMesh_1_1StripifierT" ]
];